# Generated by Django 5.0.6 on 2024-07-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homestays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("area", models.FloatField()),
                ("address", models.CharField(max_length=254)),
                ("price", models.FloatField()),
                ("discount", models.FloatField()),
                ("max_capacity", models.IntegerField()),
                ("status", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("map_key", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Homestay",
                "verbose_name_plural": "Homestays",
            },
        ),
        migrations.CreateModel(
            name="HomestayImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_key", models.CharField(max_length=100)),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homestay_images",
                        to="Homestays.homestays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homestay Image",
                "verbose_name_plural": "Homestay Images",
            },
        ),
        migrations.CreateModel(
            name="Facilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon_key", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="Homestays.homestays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bedroom", "Bedroom"),
                            ("living_room", "Living Room"),
                            ("kitchen", "Kitchen"),
                            ("dining_room", "Dining Room"),
                            ("bathroom", "Bathroom"),
                            ("balcony", "Balcony"),
                            ("laundry_room", "Laundry Room"),
                        ],
                        max_length=100,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "homestay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="Homestays.homestays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
    ]
